name: docs
description: Docs for desktop.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  desktop: ^4.0.0
  dart_style: ^2.2.4
  url_launcher: ^6.0.3
  intl: ^0.17.0
  markdown_docs_flutter: ^1.0.0

dependency_overrides:
  desktop:
    path: ../desktop
  markdown_docs_flutter:
    path: ../../markdown_docs_flutter/markdown_docs_flutter

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  assets:
    - assets/GitHub-Mark-32px.png
    - assets/GitHub-Mark-Light-32px.png

    - assets/cats/pexels-1653357.webp
    - assets/cats/pexels-3030635.webp
    - assets/cats/pexels-720684.webp
    - assets/cats/pexels-479009.webp
    - assets/cats/pexels-192384.webp
    - assets/cats/pexels-2817405.webp
    - assets/cats/pexels-3772262.webp
    - assets/cats/pexels-2255565.webp
    - assets/cats/pexels-1571724.webp
    - assets/cats/pexels-1416792.webp
    - assets/cats/pexels-4391733.webp
    - assets/cats/pexels-156321.webp
    - assets/cats/pexels-3127729.webp
    - assets/cats/pexels-96428.webp
    - assets/cats/pexels-1754986.webp
    - assets/cats/pexels-1299518.webp
    - assets/cats/pexels-5800065.webp
    - assets/cats/pexels-5456616.webp
    - assets/cats/pexels-1770918.webp
    - assets/cats/pexels-4411430.webp
    - assets/cats/pexels-1784289.webp
    - assets/cats/pexels-731553.webp
    - assets/cats/pexels-4734723.webp
    - assets/cats/pexels-1828875.webp
    - assets/cats/pexels-979503.webp
    - assets/cats/pexels-1643457.webp
    - assets/cats/pexels-5044690.webp
    - assets/cats/pexels-45170.webp
    - assets/cats/pexels-45201.webp
    - assets/cats/pexels-104827.webp
    - assets/cats/pexels-160755.webp
    - assets/cats/pexels-979247.webp
    - assets/cats/pexels-2693561.webp
    - assets/cats/pexels-2611939.webp
    - assets/cats/pexels-1687831.webp
    - assets/cats/pexels-4858815.webp

    - assets/cats_small/pexels-1653357.webp
    - assets/cats_small/pexels-3030635.webp
    - assets/cats_small/pexels-720684.webp
    - assets/cats_small/pexels-479009.webp
    - assets/cats_small/pexels-192384.webp
    - assets/cats_small/pexels-2817405.webp
    - assets/cats_small/pexels-3772262.webp
    - assets/cats_small/pexels-2255565.webp
    - assets/cats_small/pexels-1571724.webp
    - assets/cats_small/pexels-1416792.webp
    - assets/cats_small/pexels-4391733.webp
    - assets/cats_small/pexels-156321.webp
    - assets/cats_small/pexels-3127729.webp
    - assets/cats_small/pexels-96428.webp
    - assets/cats_small/pexels-1754986.webp
    - assets/cats_small/pexels-1299518.webp
    - assets/cats_small/pexels-5800065.webp
    - assets/cats_small/pexels-5456616.webp
    - assets/cats_small/pexels-1770918.webp
    - assets/cats_small/pexels-4411430.webp
    - assets/cats_small/pexels-1784289.webp
    - assets/cats_small/pexels-731553.webp
    - assets/cats_small/pexels-4734723.webp
    - assets/cats_small/pexels-1828875.webp
    - assets/cats_small/pexels-979503.webp
    - assets/cats_small/pexels-1643457.webp
    - assets/cats_small/pexels-5044690.webp
    - assets/cats_small/pexels-45170.webp
    - assets/cats_small/pexels-45201.webp
    - assets/cats_small/pexels-104827.webp
    - assets/cats_small/pexels-160755.webp
    - assets/cats_small/pexels-979247.webp
    - assets/cats_small/pexels-2693561.webp
    - assets/cats_small/pexels-2611939.webp
    - assets/cats_small/pexels-1687831.webp
    - assets/cats_small/pexels-4858815.webp