name: desktop
description: Flutter design standard for desktop. Just simple, usable wigdets to create apps. See the gallery for examples of the components used.
repository: https://github.com/adrianos42/desktop
homepage: https://adrianos42.github.io/desktop
version: 4.1.1

environment:
  sdk: '>=2.19.6 <4.0.0'
  
dependencies:
  flutter:
    sdk: flutter
    
dev_dependencies:
  pedantic: ^1.11.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  analyzer: '>=4.6.0'
  source_gen: any
  build_runner: ^2.0.0
  meta: ^1.7.0
  code_builder: ^4.3.0
  build: ^2.2.0
  built_collection: ^5.1.1

flutter:
  fonts:
    - family: IBM Plex Mono
      fonts:
        - asset: fonts/IBM_Plex_Mono/IBMPlexMono-Thin.ttf
          style: normal
          weight: 100
        - asset: fonts/IBM_Plex_Mono/IBMPlexMono-ThinItalic.ttf
          style: italic
          weight: 100
        - asset: fonts/IBM_Plex_Mono/IBMPlexMono-ExtraLight.ttf
          style: normal
          weight: 200
        - asset: fonts/IBM_Plex_Mono/IBMPlexMono-ExtraLightItalic.ttf
          style: italic
          weight: 200          
        - asset: fonts/IBM_Plex_Mono/IBMPlexMono-Light.ttf
          style: normal
          weight: 300
        - asset: fonts/IBM_Plex_Mono/IBMPlexMono-LightItalic.ttf
          style: italic
          weight: 300
        - asset: fonts/IBM_Plex_Mono/IBMPlexMono-Regular.ttf
          style: normal
          weight: 400
        - asset: fonts/IBM_Plex_Mono/IBMPlexMono-Italic.ttf
          style: italic
          weight: 400
        - asset: fonts/IBM_Plex_Mono/IBMPlexMono-Medium.ttf
          style: normal
          weight: 500
        - asset: fonts/IBM_Plex_Mono/IBMPlexMono-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: fonts/IBM_Plex_Mono/IBMPlexMono-SemiBoldItalic.ttf
          style: normal
          weight: 600
        - asset: fonts/IBM_Plex_Mono/IBMPlexMono-SemiBoldItalic.ttf
          style: italic
          weight: 600  
        - asset: fonts/IBM_Plex_Mono/IBMPlexMono-Bold.ttf
          style: normal
          weight: 700
        - asset: fonts/IBM_Plex_Mono/IBMPlexMono-BoldItalic.ttf
          style: italic
          weight: 700

    - family: IBM Plex Sans
      fonts:
        - asset: fonts/IBM_Plex_Sans/IBMPlexSans-Thin.ttf
          style: normal
          weight: 100
        - asset: fonts/IBM_Plex_Sans/IBMPlexSans-ThinItalic.ttf
          style: italic
          weight: 100
        - asset: fonts/IBM_Plex_Sans/IBMPlexSans-ExtraLight.ttf
          style: normal
          weight: 200
        - asset: fonts/IBM_Plex_Sans/IBMPlexSans-ExtraLightItalic.ttf
          style: italic
          weight: 200          
        - asset: fonts/IBM_Plex_Sans/IBMPlexSans-Light.ttf
          style: normal
          weight: 300
        - asset: fonts/IBM_Plex_Sans/IBMPlexSans-LightItalic.ttf
          style: italic
          weight: 300
        - asset: fonts/IBM_Plex_Sans/IBMPlexSans-Regular.ttf
          style: normal
          weight: 400
        - asset: fonts/IBM_Plex_Sans/IBMPlexSans-Italic.ttf
          style: italic
          weight: 400
        - asset: fonts/IBM_Plex_Sans/IBMPlexSans-Medium.ttf
          style: normal
          weight: 500
        - asset: fonts/IBM_Plex_Sans/IBMPlexSans-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: fonts/IBM_Plex_Sans/IBMPlexSans-SemiBoldItalic.ttf
          style: normal
          weight: 600
        - asset: fonts/IBM_Plex_Sans/IBMPlexSans-SemiBoldItalic.ttf
          style: italic
          weight: 600  
        - asset: fonts/IBM_Plex_Sans/IBMPlexSans-Bold.ttf
          style: normal
          weight: 700
        - asset: fonts/IBM_Plex_Sans/IBMPlexSans-BoldItalic.ttf
          style: italic
          weight: 700

    - family: IBM Plex Serif
      fonts:
        - asset: fonts/IBM_Plex_Serif/IBMPlexSerif-Thin.ttf
          style: normal
          weight: 100
        - asset: fonts/IBM_Plex_Serif/IBMPlexSerif-ThinItalic.ttf
          style: italic
          weight: 100
        - asset: fonts/IBM_Plex_Serif/IBMPlexSerif-ExtraLight.ttf
          style: normal
          weight: 200
        - asset: fonts/IBM_Plex_Serif/IBMPlexSerif-ExtraLightItalic.ttf
          style: italic
          weight: 200          
        - asset: fonts/IBM_Plex_Serif/IBMPlexSerif-Light.ttf
          style: normal
          weight: 300
        - asset: fonts/IBM_Plex_Serif/IBMPlexSerif-LightItalic.ttf
          style: italic
          weight: 300
        - asset: fonts/IBM_Plex_Serif/IBMPlexSerif-Regular.ttf
          style: normal
          weight: 400
        - asset: fonts/IBM_Plex_Serif/IBMPlexSerif-Italic.ttf
          style: italic
          weight: 400
        - asset: fonts/IBM_Plex_Serif/IBMPlexSerif-Medium.ttf
          style: normal
          weight: 500
        - asset: fonts/IBM_Plex_Serif/IBMPlexSerif-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: fonts/IBM_Plex_Serif/IBMPlexSerif-SemiBoldItalic.ttf
          style: normal
          weight: 600
        - asset: fonts/IBM_Plex_Serif/IBMPlexSerif-SemiBoldItalic.ttf
          style: italic
          weight: 600  
        - asset: fonts/IBM_Plex_Serif/IBMPlexSerif-Bold.ttf
          style: normal
          weight: 700
        - asset: fonts/IBM_Plex_Serif/IBMPlexSerif-BoldItalic.ttf
          style: italic
          weight: 700

    - family: SharpMaterialIcons
      fonts:
        - asset: fonts/Material_Icons_Sharp_Regular/MaterialIconsSharp-Regular.otf